"""
UI Map Loader.

Loads ui_map.json files generated by POM discovery tools and converts them to FSM states.
This allows seeding FSM discovery with structural knowledge from POM tools.
"""

import json
import logging
from typing import Any
from pathlib import Path

from model_resilience_core import UIState
from model_resilience_core.fingerprinting import StateFingerprinter
from aria_state_mapper.discovery.state_classifier import StateClassifier

logger = logging.getLogger(__name__)


class UIMapLoader:
    """Loader for ui_map.json generated by the discovery tool."""
    
    @staticmethod
    def load_map(path: str) -> dict[str, Any]:
        """Load and parse ui_map.json.
        
        Args:
            path: Path to ui_map.json file
            
        Returns:
            Dictionary containing the map data
        """
        try:
            with open(path, 'r') as f:
                data = json.load(f)
            
            logger.info("Loaded UI map from %s: %d pages, %d elements", 
                       path, 
                       data.get("statistics", {}).get("page_count", 0),
                       data.get("statistics", {}).get("element_count", 0))
            return data
        except Exception as e:
            logger.error("Error loading UI map from %s: %s", path, e)
            return {}

    @staticmethod
    def extract_states(map_data: dict[str, Any]) -> list[UIState]:
        """Convert map pages into initial UIStates.
        
        Args:
            map_data: Loaded map data
            
        Returns:
            List of UIState objects
        """
        states = []
        graph = map_data.get("graph", {})
        nodes = graph.get("nodes", [])
        
        # Index elements by page URL for efficient lookup
        elements_by_page = {}
        nodes_by_id = {node.get("id"): node for node in nodes}
        
        # Build page -> elements map from edges
        edges = graph.get("edges", [])
        for edge in edges:
            if edge.get("edge_type") == "ON_PAGE":
                elem_id = edge.get("source")
                page_url = edge.get("target")
                
                elem_node = nodes_by_id.get(elem_id)
                if elem_node:
                    if page_url not in elements_by_page:
                        elements_by_page[page_url] = []
                    elements_by_page[page_url].append(elem_node)

        # Create states from pages
        for node in nodes:
            if node.get("node_type") == "Page":
                url = node.get("id")
                
                # Create rudimentary fingerprint from static data
                fingerprint = {
                    "url_pattern": StateFingerprinter._extract_url_pattern(url),
                    "title": node.get("title", ""),
                    "key_elements": []
                }
                
                # Add known elements to fingerprint/state
                if url in elements_by_page:
                    for elem in elements_by_page[url]:
                        # Convert map element to descriptor format
                        descriptor = {
                            "element_type": elem.get("element_type"),
                            "locators": {
                                "css": elem.get("locator_value"),
                                "text": elem.get("text") or "",
                                "test_id": elem.get("button_id") or elem.get("name")
                            },
                            "metadata": {
                                "friendly_name": elem.get("friendly_name")
                            }
                        }
                        fingerprint["key_elements"].append(descriptor)
                
                # Classify
                state_type, state_id = StateClassifier.classify_state(fingerprint)
                
                state = UIState(
                    state_id=state_id,
                    state_type=state_type,
                    fingerprint=fingerprint,
                    verification_logic={"url_pattern": fingerprint["url_pattern"]},
                    element_descriptors=fingerprint["key_elements"]
                )
                states.append(state)
                
        return states

